[env:esp32-s3-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = waveshare_esp32_s3_touch_lcd_4_3_b
framework = arduino

monitor_speed = 115200
upload_speed = 921600

board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_build.f_flash = 80000000L
board_build.flash_mode = qio

build_unflags =
    -std=gnu++11

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -I include
    -std=gnu++17

lib_deps =
    https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#v1.0.4
    https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.1
    https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.3.0